### ISSUE TITLE
Get exported variables into next job

### ISSUE THREAD

**Issue by KevinMSampson** [ci-cd-scripts/called-workflows#25]
https://github.com/ci-cd-scripts/called-workflows/blob/8e128efa67ce3d3ae7ae02e0f322774cae4538f9/.github/workflows/issueops.yml#L110

The called workflow can be run when the values are static but there's something missing that's causing the reused workflow to fail without details.
Find out how to print `needs`, `jobs`, `steps`, etc variables to the log to see what's available and what's missing

**Comment by KevinMSampson** [comment]
Environment not able to be set for Reused workflows - trying to have the called workflow use the environment secret directly

**Comment by KevinMSampson** [comment]
test

**Comment by KevinMSampson** [comment]
I was able to get this to work by changing the called workflow to accept strings instead of booleans.
Job outputs are strings and fail if booleans are expected.

# Next
The `demilestoned` event may not include the issue labels, causing them to be skipped.
**Confirm this**

**Comment by KevinMSampson** [comment]
It works!
The `caller` needs to pass the variables and environment name for the `called` workflow to use.
The `called` workflow must reference the environment itself, but that means it must accept a variable with the environment name in it: 

### caller workflow:
```
...
jobs:
  job:
    uses: ci-cd-scripts/called-workflows/.github/workflows/workflow-name.yml@main
    with:
      env: "env-name"
    secrets:
      caller-secret: ${{ secrets.ENV_SECRET }}
```
### called workflow:
```
on:
  # Allows you to reuse this workflow from other workflows
  workflow_call:
    inputs:
      env:
        description: 'Environment for the called workflow to use
        required: true
    secrets:
      caller-secret:
        required: true
...
jobs:
  job:
    environment: ${{ inputs.env }}
    steps:
      ...
```
Set for the jobs using the env secrets: `environment: ${{ inputs.env }}`
